### ISSUE TITLE
Not working in Modx 2.6.1

### ISSUE THREAD

**Issue by sfaessler** [Mark-H/importX#69]
I've added a simple CSV File like this one and tried to import it.

pagetitle;content
Test;Hallo

Console opens starts to run bit it happens nothing. After a couple of minutes I'm closing the console popup but there are no new documents?

How can this problem be solved?

Thanks in advance.

**Comment by Mark-H** [comment]
Works fine here, except for some notices (#57 is the newly created resource). 

````
Console running...
Attempted to set execution time to infinite. Max execution time currently: infinite.
Running pre-import tests on submitted data...
No errors in pre-import found. Preparing import values...
No errors found while checking the import values: 1 items found. Running import...
`57` was requested but no alias was located.
Resource with id 57 was not found in context web
PHP notice: Undefined index: source
PHP notice: Undefined index: keywords
Importing completed. 1 resources have been imported.
````

Can you check for errors in the browsers' developer tools?

**Comment by sfaessler** [comment]
Please see screenshots attached. One is from testing with Raw CSV file:

pagetitle
Test1
Test2

The other one is after uploading the CSV file attached here.

![importx2](https://user-images.githubusercontent.com/13064849/36726062-b6d6cdaa-1bb8-11e8-9bd4-8022be10a862.png)
![importx](https://user-images.githubusercontent.com/13064849/36726063-b6f914dc-1bb8-11e8-9c16-111cf02656b3.png)

**Comment by Mark-H** [comment]
Attached file also works fine in my testing on 2.6.1.

The error shown in the last screenshot (`SyntaxError: expected expression, go t'<'` in `Ext.uit.JSON</this.decide</<`) means there is HTML (99% of the time, showing a PHP error) in the response from one of the AJAX requests. 

Please open your browsers' developer tools before starting the import, and look at the network tab. One of the requests that go out will have the HTML in its response. Please find that error and post that here.

**Comment by sfaessler** [comment]
Works now. Thanks for your help. /assets was writable by group and throw an error message.
