### ISSUE TITLE
Performance issues in MODX 2.6.5

### ISSUE THREAD

**Issue by robh76** [Mark-H/importX#70]
I've been using ImportX to import 10,000+ records no problem. However since upgrading to MODX 2.6.5, it's started running in really slowly and I'm getting a string of error messages (in blue)... "mysql_context.. slow mysql query, consider setting use_context_resource _able to false", which I've done and it's made no difference, I'm still seeing these messages. Also, I'm getting messages in red, similar to "Unable to update cache in context ID" (sorry that's not the exact wording but similar)... I've tried clearing the cache, uninstalling and reinstalling ImportX, running set up again but no avail. Any help appreciated. Thanks!

**Comment by robh76** [comment]
Thanks Mark,

I have about 90,000 resources on the site & ImportX was running quite happily at around 1000 resources every 10 minutes but now it can take an hour or more to import 1000.

Latest twist is that it’s causing my entire VPS to crash, so I’m not entirely sure whether the slow ImportX running is just a symptom of something else or the cause. I’ve got masses of spare capacity & memory on the server so should be OK in that regard.

I’m trying to get help from my hosting provider at the moment.

Rob

**Comment by robh76** [comment]
Hi Mark,

Thanks for your response… I’ve solved it. Nothing to do with Modx 2.6.5 or ImportX, which is a great plugin by the way.. I rely on it a lot.

My Modx .trash folder had about 100GB of junk in it, mostly from manually clearing the cache after constantly importing tens of thousands of .lines of CSV file using ImportX - I’ll know for future.

Best Regards
Rob Horn

**Comment by Mark-H** [comment]
Glad to hear you figured it out!
